[package]
name = "ui"
version = "0.1.0"
authors = ["AdrienDML <adriendml99@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18.0"

# [[bin]]
# name = "ui"
# path = "src/main.rs"